#!/usr/bin/env bash
# displays story about elements separated out from /etc/passwd file

IFS=":"

while read -r row
do
	p=$(echo $row)
	set $p
	USERNAME=$1
	PASSWORD=$2
	USER_ID=$3
	GROUP_ID=$4
	USER_ID_INFO=$5
	HOME_DIRECTORY=$6
	COMMANDSHELL=$7
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides "$COMMANDSHELL". $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "/etc/passwd"
