#!/usr/bin/env bash
# displays each hour from 0-12 with minutes 1-59 between each hour

i=0

while [ $i -le 12 ]
do
	j=1
	echo "Hour: $i"
	while [ $j -le 59 ]
	do
		echo "$j"
		j=$(( j+1 ))
	done
	i=$(( i+1 ))
done	
