#!/usr/bin/env bash
# runs series of tests on school file to determine if it exists, if it is empty, and if it is a regular file

# tests if school exists
if test -e "$school"
then
	echo "school file exists"

	# tests if school is empty
	if test -s "$school"
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	
	# tests if school is a regular file
	if test -f "$school"
	then
		echo "school is a regular file"
	fi
	
else
	echo "school file does not exist"
fi
