#!/usr/bin/env bash
# runs series of tests on school file to determine if it exists, if it is empty, and if it is a regular file

s="school"

# tests if school exists
if [ -e "$s" ]
then
	echo "school file exists"

	# tests if school is empty
	if [ -s "$s" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	
	# tests if school is a regular file
	if [ -f "$s" ]
	then
		echo "school is a regular file"
	fi
	
else
	echo "school file does not exist"
fi
